### ISSUE TITLE
Modifications on GitHub according to the draft

### ISSUE THREAD

**Issue by ranocha** [ketch/RK-Opt#50]
1. Currently, we have
    
    > Matlab scripts to search for Runge-Kutta methods that are optimal in terms of SSP coefficient

    as brief description of RK-Opt on GitHub but

    > A package for the design of numerical ODE solvers

    in the draft.

2. Currently, the title on GitHub is

    > RK-opt

    but we use

    > RK-Opt

    in the draft. You can just rename the repository on GitHub - capitalization does not matter in URLs (and GitHub would forward all traffic otherwise).

**Comment by ketch** [comment]
Okay, I've changed things now to consistently use "O" instead of "o".  However, it does not seem to be true in this case that capitalization does not matter.  The change to the Readme in 149a090a13b24e91b74562ad555f66afce807dd9 broke the link to the docs.  I renamed the directory on the numerics server so that now it works again.  But now if you try loading it with "o" you will get a 404.  So there might be broken links in other places.

**Comment by ranocha** [comment]
I'm sorry for that. At least for GitHub repositories, capitalization does  not matter. For example, I can access this issue via https://GiThUb.com/KeTcH/rK-oPt/issues/50.

**Comment by ketch** [comment]
Right; I think it’s because the docs are hosted on a Unix server and Unix is case-sensitive. Anyway, it will be good to be consistent with this everywhere.

**Comment by ketch** [comment]
I realized that the easy solution was just to create a soft link on the server so that RK-opt redirects to RK-Opt.  This avoids the need to find and replace all existing links.

**Comment by ranocha** [comment]
That's a neat idea :+1:
